version: '3.8'

services:
  flask_app:
    build:
      context: ../
      dockerfile: ./Scores/Dockerfile
    image: asdumitrescu/wog_scores_flask
    ports:
      - "8777:5000"
    volumes:
      - ./Scores.txt:/app/Scores.txt
      - ./Last_scores.txt:/app/Last_scores.txt
      - ../name.txt:/app/name.txt

    environment:
      - FLASK_APP=MainScores.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    command: [ "flask", "run", "--host=0.0.0.0", "--port=5000" ]