version: '3.8'

services:
  flask_app:
    build:
      context: ../
      dockerfile: ./Scores/Dockerfile
    image: asdumitrescu/wog_scores_flask

    volumes:
      - ./Scores.txt:/app/Scores.txt
      - ./Last_scores.txt:/app/Last_scores.txt
      - ../name.txt:/app/name.txt
    ports:
      - "8777:5000"
    environment:
      - FLASK_APP=MainScores.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    command: [ "flask", "run",]
    networks:
      scores_network:
        ipv4_address: 172.25.0.5

networks:
  scores_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.5/16
